version: '3.8'
services:
  
  db:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: postfixadmin
      MYSQL_USER: postfixadmin
      MYSQL_PASSWORD: example

  postfix:
    image: catatnight/postfix
    environment:
      - MAIL_DOMAIN=mail.teste.com
      - MAIL_SERVER_HOSTNAME=mail.teste.com     
    ports:
        - "26:25"
  
  postfixadmin:
    depends_on:
      - db
    image: postfixadmin
    container_name: postfixadmin
    ports:
      - 8000:80
    environment:
      POSTFIXADMIN_DB_TYPE: mysqli
      POSTFIXADMIN_DB_HOST: db
      POSTFIXADMIN_DB_USER: postfixadmin
      POSTFIXADMIN_DB_NAME: postfixadmin
      POSTFIXADMIN_DB_PASSWORD: example
    volumes:
      - ./config/config.inc.php:/var/www/html/config.inc.php
      - ./config/config.local.php:/var/www/html/config.local.php
    restart: unless-stopped
